### PR TITLE
replaced Option interface by simpler func type

### PR DESCRIPTION
**Pull request by shogg**
The interface couldn't be implemented outside the problem package because of:
- private apply function
- private Problem.data field

Also consider renaming ToWriter to WriteTo.

### CODE REVIEW

**Comment by mschneider82** [comment]
Hi thanks for the pull request, i am not sure if i want to replace the apply and optionFunc, because i think naming it is a good thing.

I also checked renaming to WriteTo, but io.WriteTo is a different interface since it returns int64 not int. Sure we could convert int to int64 but it this good practice?
Should we rename it and break the io.WriteTo interface?

**Comment by mschneider82** [comment]
ok  I checked some WriteTo implementations, it seems to be good practive converting int to int64 to satisfy that interface https://golang.org/src/bytes/reader.go?s=3379:3437#L149

**Comment by shogg** [comment]
I didn't remove Option. I only changed the type in a compatible way. As you can see there aren't any changes to the test code. The extra interface was not useful. It was redundant code without purpose, impossible to implement. So removing the interface and replacing it by a concrete type simplified the code.

By renaming ToWriter to WriteTo I didn't meant to implement io.WriterTo. I meant to switch to a more commonly used naming scheme. There are many WriteTo methods in the standard library that don't implement io.WriterTo. When I first read ToWriter my first impression was it would convert a Problem to a Writer.

**Comment by shogg** [comment]
Time to abandon.

**Pull request closed without merging**
